#%RAML 1.0
title: My API with Types
mediaType: application/json
baseUri: https://{env}.domain.com
baseUriParameters:
  env:
    displayName: Environment
    type: string
    enum: [staging, api]
    example: staging
/{orgId}:
  get:
    queryParameters:
      q:
        type: string
        example: addClass+in:file+language:js+repo:jquery/jquery
        required: true
        description: |
          The search terms. This can be any combination of the supported code search parameters: 'Search In' Qualifies which fields are searched.
          With this qualifier you can restrict the search to just the file contents, the file path, or both.
          'Languages' Searches code based on the language it's written in. 'Forks' Filters repositories based on the number of forks, and/or whether code from forked repositories should be included in the results at all.
        displayName: q
        maxLength: 120
      sort:
        example: sort=stars
        required: true
        type: string
      order:
        required: true
        type: string
        enum: [desc, asc]
      optionalParameter:
        required: false
        type: string
      arrayQueryParameter:
        required: true
        type: string[]
