language: node_js
node_js: stable
before_script:
- bower install --silent
addons:
  sauce_connect: true
script:
- npm run lint
- polymer test --plugin sauce --job-name "raml-request-parameters-editor:${TRAVIS_BRANCH}"
  --build-number=${TRAVIS_BUILD_NUMBER}
cache:
  directories:
  - node_modules
branches:
  only:
  - stage
  - develop
after_success:
- node tasks/ci.js
env:
  global:
  - secure: Tpr/jVHCr4LWyuJeBUYmVm+mLb2G5O9cEHs4jXLfBmOynG/pnMJeOz54TxzPAAoAeFwGqnnQILMx9hnxjPzk6G4++gi9uSSkRh0gn/3gXWJhKMTEO/a/PGp8SCTmrWNswFD+H7FC4XOo1KVzjwyrdeIWkop2Zq9YCTKa1AEVXKBx/wQTBEeuiJAYRTHW/tD+UsAkQtcbvRHfC0ojqK0h8zzSKfC6NbG+AawNKSrVkrwDJmimHzdKvsKV69iYRkSDsT2CF2qpEfzy9qfvpSVHL6Cccj8zsW+VawLmyFOdVdMqoNQ00D03c7jDe8xeQEvrKHf1yx8W75CP/omrDXGk6rd0maT1PFzYfF4F3FzwMKpER3GrQx06l31nBsDxRFXEkkAvVCau1FsBTpqTou2fmWASTCq6XZAHX2LH1X2zYlyf/h9meee6DXC0hzFHNvytOpA3mwo45We619Q+Js0jOHUv6MyGDd3rQLr4vl5I6bYjDbGfvSuWWKZcFg+AtX6BKtPlki+UwfWNOjZ/1CifdZDacTm2w3/qqt4F3Wy7lo6D70PByk5ioCBEgwUnrmhAJeikQN2fmJX45L7do+sMVDKBnGQ51i2S9kJuBser4VQ0nJ/prSYLFbNx1h5GtgdICjVokkazRD1qV3MRy8rw/Ct34M1gBkjWsKBvjC+qfB8=
  - secure: ma3AyoGbMMGhaZnDu0ngquE2jaFnIhffkepPFvNgjY7HaU+32auH21nlyHD6bbsoeIJLIJ7epk7WtA86+7BGe0c7iTO6SGML6INE3y7L1rnmpSRC4LzkakppauzkfFYgyeEYO1PIswZBfrc31ap0BRUtr6MbBIFVZXiVIz/d4aWcp5c5ez5Y/0+E3LPJ1B7gteLQzmcfupXngOz9W9c9VIzsyoTxdqR0/8MMuZBSZfmdMvzVfj9jM5fZQP4R/Qt4orpRahDZnAcLMfEHrGxAb1LjbkovTH/p2NqHfBQCEtej8srYo46kiQgbfajtbjDo/yBncZpJNj/8tlTMP4Pybw8hr5G1/YvmjkgYfd/2/J866eW6qFMekglavFLKgXnEAjVKm6cnHdQNGlzXnxSn5U/u0gFx4UvfrL2uzEjgmpBgiqOpOCueGxif7nKNkNVr/JTcECZ/h4QNvygy7tITxeJs6BBv3tRI5nbLoVfmBJ8m1hw2cvR4i1+GWT4eagiSBj66iZpA7HJ7zSf37cnaPHVAiCanRzACiQ1cpR+N/zuVTm4DuWu0REOpOl9qJV0BuD6UIztz/wfWDTVgFZbsJRapKe48z3K5Y5zprj7/sMNoyqewj8MukypffOzxaIqRJCEkEp4H1MgZGwdJrgjgHIonAQuHELNeBnkEdDIAPxc=
